apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  namespace: backend
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: backend
spec:
  replicas: 1
  strategy:
    type: Recreate   # 단일 노드 + RWO PVC → Recreate가 안전
  selector:
    matchLabels: { app: elasticsearch }
  template:
    metadata:
      labels: { app: elasticsearch }
    spec:
      initContainers:
        - name: install-nori
          image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
          command: ["sh","-c"]
          args:
            - |
              if [ ! -d /usr/share/elasticsearch/plugins/analysis-nori ]; then
                elasticsearch-plugin install --batch analysis-nori
              fi
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/elasticsearch/plugins
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
          ports:
            - containerPort: 9200
          env:
            - { name: discovery.type, value: single-node }
            - { name: xpack.security.enabled, value: "false" }  # 내부 테스트용
            - { name: ES_JAVA_OPTS, value: "-Xms512m -Xmx512m"  } # 줄임
          volumeMounts:
            - { name: data,    mountPath: /usr/share/elasticsearch/data }
            - { name: plugins, mountPath: /usr/share/elasticsearch/plugins }
          readinessProbe:
            httpGet: { path: /, port: 9200 }
            periodSeconds: 10
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
#            requests: { cpu: "250m", memory: "768Mi" }  # 노드가 빠듯하면 낮춰둬도 OK
#            limits:   { cpu: "1",    memory: "2Gi" }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: es-data
        - name: plugins
          emptyDir: {}   # initContainer가 여기에 nori를 설치
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: backend
spec:
  type: ClusterIP
  selector: { app: elasticsearch }
  ports:
    - name: http
      port: 9200
      targetPort: 9200
